---
version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - "kampfmoehre"
  - directory: /
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      jest:
        patterns:
          - "jest"
          - "jest-circus"
          - "@types/jest"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - "kampfmoehre"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
