stages:
  - release

release:master:
  image: registry.droidnet.de/buildfarm/docker-build-container/alpine/nodejs:latest
  stage: release
  only:
    - master
  tags:
    - docker
  script:
    - npm ci
    - npx semantic-release
